In [ ]:
# dot

In [2]:
from keras import backend as K
import numpy as np
import tensorflow as tf
tensor1 = tf.constant([[1,1],[2,2],[3,3],[4,4]])
tensor2 = tf.constant([[11,11,11,11],[22,22,22,22]])
mul = K.dot(tensor1,tensor2)

with tf.Session() as sess:
    output = sess.run(mul)
    print(output)

[[ 33  33  33  33]
 [ 66  66  66  66]
 [ 99  99  99  99]
 [132 132 132 132]]


In [15]:
from keras import backend as K
import numpy as np
import tensorflow as tf
tensor1 = tf.constant([[1],[2]])
tensor2 = tf.constant([[3,4]])
mul = K.dot(tensor1,tensor2)

with tf.Session() as sess:
    output = sess.run(mul)
    print(output)

[[3 4]
 [6 8]]


In [17]:
from keras import backend as K
import numpy as np
import tensorflow as tf

tensor1 = tf.constant([[[1],[2]], [[5],[6]]])
print(tensor1.shape)
tensor2 = tf.constant([[3,4]])
print(tensor2.shape)
mul = K.dot(tensor1,tensor2)

with tf.Session() as sess:
    output = sess.run(mul)
    print(output)

(2, 2, 1)
(1, 2)
[[[ 3  4]
  [ 6  8]]

 [[15 20]
  [18 24]]]


In [ ]:
# batch-dot

In [19]:
from keras import backend as K
import numpy as np
import tensorflow as tf

tensor1 = tf.constant([[[1],[2]], [[5],[6]]])
print(tensor1.shape)
tensor2 = tf.constant([[[3,4]], [[3,4]]])
print(tensor2.shape)
mul = K.batch_dot(tensor1,tensor2)

with tf.Session() as sess:
    output = sess.run(mul)
    print(output)

(2, 2, 1)
(2, 1, 2)
[[[ 3  4]
  [ 6  8]]

 [[15 20]
  [18 24]]]
